openapi: 3.1.0
info:
  title: GOV.UK Search and Content API
  description: Publicly accessible API for searching GOV.UK content and retrieving detailed content data.
  version: v1.1.0
servers:
  - url: https://www.gov.uk/api
paths:
  /search.json:
    get:
      description: Search for GOV.UK content based on various parameters.
      operationId: SearchGovUkContent
      parameters:
        - name: q
          in: query
          description: Search query. Any well-formed UTF-8 values are allowed.
          required: true
          schema:
            type: string
        - name: count
          in: query
          description: Limits the number of results returned. Default is 10, maximum is 1500.
          required: false
          schema:
            type: integer
        - name: filter_public_timestamp
          in: query
          description: "Filters documents published within a specific date range. Format: from:<date>,to:<date>. Dates are ISO
            formatted and inclusive."
          required: false
          schema:
            type: string
      deprecated: false
      responses:
        "200":
          description: Successful response with search results
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResults"
        "422":
          description: Invalid request due to unknown or invalid parameters
  /content/{base_path}:
    get:
      description: Retrieve content details for a specific GOV.UK page based on its path.
      operationId: GetGovUkContent
      parameters:
        - name: base_path
          in: path
          description: The path of the content on GOV.UK, without the leading slash.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response with the content details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContentDetails"
        "404":
          description: Content not found
components:
  schemas:
    Organisation:
      type: object
      properties:
        organisation_type:
          type: string
          description: Type of the organisation, e.g., ministerial_department, non_ministerial_department.
        organisation_state:
          type: string
          description: Current state of the organisation, e.g., live, closed.
        acronym:
          type: string
          description: Acronym of the organisation.
        content_id:
          type: string
          description: Unique content identifier of the organisation.
        link:
          type: string
          description: Link to the organisation's page.
        title:
          type: string
          description: Full title of the organisation.
        analytics_identifier:
          type: string
          description: Analytics identifier for tracking purposes.
        organisation_crest:
          type: string
          description: The crest used by the organisation.
        organisation_brand:
          type: string
          description: Branding of the organisation.
        child_organisations:
          type: array
          description: List of child organisations.
          items:
            type: string
        parent_organisations:
          type: array
          description: List of parent organisations.
          items:
            type: string
        superseded_organisations:
          type: array
          description: List of superseded organisations.
          items:
            type: string
        logo_formatted_title:
          type: string
          description: Formatted title displayed alongside the organisation logo.
        public_timestamp:
          type: string
          format: date-time
          description: Timestamp of the last update for the organisation.
        slug:
          type: string
          description: Slug identifier of the organisation.
    SearchResults:
      type: object
      properties:
        total:
          type: integer
          description: Total number of search results.
        start:
          type: integer
          description: The starting index of the returned results.
        results:
          type: array
          description: An array of search result objects.
          items:
            type: object
            properties:
              description:
                type: string
                description: A brief summary of the document.
              format:
                type: string
                description: The format of the document, e.g., transaction, guide.
              link:
                type: string
                description: The link to the document.
              organisations:
                type: array
                description: List of associated organisations.
                items:
                  $ref: "#/components/schemas/Organisation"
              public_timestamp:
                type: string
                format: date-time
                description: Timestamp when the document was last published or updated.
              title:
                type: string
                description: The title of the document.
              world_locations:
                type: array
                description: List of associated world locations.
                items:
                  type: string
              topical_events:
                type: array
                description: List of associated topical events.
                items:
                  type: string
              organisation_content_ids:
                type: array
                description: List of content IDs for associated organisations.
                items:
                  type: string
              expanded_organisations:
                type: array
                description: Expanded list of associated organisations with detailed information.
                items:
                  $ref: "#/components/schemas/Organisation"
              index:
                type: string
                description: Index where the document is stored, e.g., govuk, government.
              es_score:
                type:
                  - number
                  - "null"
                description: Elasticsearch relevance score.
              _id:
                type: string
                description: Unique identifier of the document.
              elasticsearch_type:
                type: string
                description: Type of Elasticsearch document.
              document_type:
                type: string
                description: Type of document, e.g., edition.
        aggregates:
          type: object
          description: Aggregated search result data.
        suggested_queries:
          type: array
          description: List of suggested queries.
          items:
            type: string
        suggested_autocomplete:
          type: array
          description: List of suggested autocomplete queries.
          items:
            type: string
        es_cluster:
          type: string
          description: Elasticsearch cluster identifier.
    ContentDetails:
      type: object
      properties:
        analytics_identifier:
          type: string
          nullable: true
          description: Analytics identifier for tracking purposes.
        base_path:
          type: string
          description: The base path of the content on GOV.UK.
        content_id:
          type: string
          description: Unique content identifier of the content.
        description:
          type: string
          description: Brief description of the content.
        details:
          type: object
          description: Detailed information about the content.
          properties:
            external_related_links:
              type: array
              description: List of external related links.
              items:
                type: object
                properties:
                  title:
                    type: string
                    description: Title of the external link.
                  url:
                    type: string
                    description: URL of the external link.
            hide_chapter_navigation:
              type: boolean
              description: Flag indicating if chapter navigation should be hidden.
            parts:
              type: array
              description: List of parts or sections in the content.
              items:
                type: object
                properties:
                  body:
                    type: string
                    description: The HTML content of the part.
                  slug:
                    type: string
                    description: Slug identifier for the part.
                  title:
                    type: string
                    description: Title of the part.
        document_type:
          type: string
          description: The type of the document (e.g., guide, answer).
        first_published_at:
          type: string
          format: date-time
          description: Timestamp when the content was first published.
        public_updated_at:
          type: string
          format: date-time
          description: Timestamp when the content was last updated.
        title:
          type: string
          description: Title of the content.
        web_url:
          type: string
          description: The web URL of the content on GOV.UK.
